[package]
name = "xhacklight"
version = "0.1.0"
authors = ["SillyFreak <sillyfreak.ck@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true

[dependencies]
anyhow = "1.0.31"
